name: Linting
on: push
jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          src: "test"
      - uses: jakebailey/pyright-action@v2
        with:
          working-directory: test
      - uses: isort/isort-action@v1
        with:
          sort-paths: "test"
          requirements-files: "requirements-pip.txt"
