name: Test Neureka
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-neureka:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: pulp-nnx

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            pulp-nnx/test/requirements.txt
            pulp-nnx/test/workflow-requirements/requirements-run-pulp-sdk.txt

      - name: Install Python Packages
        run: |
          pip install \
            -r pulp-nnx/test/requirements.txt \
            -r pulp-nnx/test/workflow-requirements/requirements-run-pulp-sdk.txt

      - name: Restore Cached Gnu Toolchain
        uses: actions/cache/restore@v4
        with:
          path: toolchain/gnu
          key: toolchain-gnu
          fail-on-cache-miss: true

      - name: Restore Cached PULP-SDK
        uses: actions/cache/restore@v4
        with:
          path: pulp-sdk
          key: pulp-sdk
          fail-on-cache-miss: true

      - name: Run test
        run: |
          export PULP_RISCV_GCC_TOOLCHAIN=$GITHUB_WORKSPACE/toolchain/gnu
          source pulp-sdk/configs/siracusa.sh
          cd pulp-nnx/test
          pytest test.py --test-dir tests --recursive --accelerator neureka --build-flow=make --wmem=tcdm
          pytest test.py --test-dir tests --recursive --accelerator neureka --build-flow=make --wmem=sram
