name: Test Neureka
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/pulp-platform/pulp-nnx:main-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run test
        shell: bash
        working-directory: test
        run: |
          source /pulp-sdk/configs/siracusa.sh
          pytest test.py -T tests -R -A neureka
