name: Test Neureka v2
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-neureka-v2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: pulp-nnx

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            pulp-nnx/test/requirements.txt
            pulp-nnx/test/workflow-requirements/requirements-run-gvsoc.txt

      - name: Install Python Packages
        run: |
          pip install \
            -r pulp-nnx/test/requirements.txt \
            -r pulp-nnx/test/workflow-requirements/requirements-run-gvsoc.txt

      - name: Restore Cached Gnu Toolchain
        uses: actions/cache/restore@v4
        with:
          path: toolchain/gnu
          key: toolchain-gnu
          fail-on-cache-miss: true

      - name: Restore Cached PULP-SDK
        uses: actions/cache/restore@v4
        with:
          path: pulp-sdk
          key: pulp-sdk
          fail-on-cache-miss: true

      - name: Restore Cached GVSoC
        uses: actions/cache/restore@v4
        with:
          path: gvsoc/install
          key: gvsoc
          fail-on-cache-miss: true

      - name: Run test
        run: |
          export PULP_SDK_HOME=$GITHUB_WORKSPACE/pulp-sdk
          export TOOLCHAIN_GNU_INSTALL_DIR=$GITHUB_WORKSPACE/toolchain/gnu
          export GVSOC=$GITHUB_WORKSPACE/gvsoc/install/bin/gvsoc
          cd pulp-nnx/test
          pytest test.py --test-dir=tests --recursive --accelerator=neureka_v2 --build-flow=cmake --wmem=mram --app=pulp-nnx
          pytest test.py --test-dir=tests --recursive --accelerator=neureka_v2 --build-flow=cmake --wmem=mram --app=pulp-nnx-hal
